apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-hello-world-is
  namespace: ace-hello-world
spec:
  enableMetrics: true
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9483'
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationNonProductionFREE
  adminServerSecure: true
  forceFlowHTTPS:
    enabled: true
    secretName: ace-certificate-secret
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  version: 12.0.7.0-r2
  replicas: 1
  barURL: https://nexus-nexus.apps.eyf1y3w8.eastus.aroapp.io/repository/myrepo/ace-hello-world/MyExampleApplication/unspecified/MyExampleApplication-unspecified.bar
