apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ace-helloworld-integrationserver.yaml
  - certificate.yaml
  - self-signed-issuer.yaml
  - nexus-barauth.yaml
  #- hpa.yaml
