apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eventlistener-certificate
spec:
  secretName: eventlistener-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - ace-hello-world
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - '*'
  issuerRef:
    name: ace-selfsigned-issuer
